package aiku_main.application_event.event;

public enum PointChangeReason {
    SCHEDULE_ENTER, SCHEDULE_EXIT, SCHEDULE_REWARD,
    BETTING, BETTING_CANCLE, BETTING_REWARD,
    RACING, RACING_CANCEL, RACING_REWARD,
    SHOP, SHOP_CANCEL, EVENT, EVENT_CANCEL, PAYMENT, PAYMENT_CANCEL
}
