package common.kafka_message;

public enum PointChangeReason {
    SCHEDULE_ENTER, SCHEDULE_EXIT, SCHEDULE_REWARD,
    BETTING, BETTING_CANCLE, BETTING_REWARD,
    RACING, RACING_CANCEL, RACING_REWARD, RACING_DRAW,
    EVENT, EVENT_CANCEL,

    // 이하 사용 X
    SHOP, SHOP_CANCEL, PAYMENT, PAYMENT_CANCEL
}
